notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python
python: 3.6

sudo: required

services:
  - docker

jobs:
  include:
  - stage: docker compose build
    script: make docker-build
  - stage: test
    script:
      - pip install -q pycodestyle
      - make lint
      - docker-compose run --rm arcusd scripts/test.sh
  - stage: code coverage
    script:
      - make code-coverage-upload
