notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python

sudo: required

services:
  - docker

jobs:
  include:
  - stage: docker build and test
    python: 3.6
    before_install:
      - cp env.template .env
      - docker-compose up -d
    install:
      - docker-compose exec arcusd make install-dev
    script:
      - docker-compose exec arcusd make test
    after_success:
      # env variables taken from
      # https://github.com/coveralls-clients/coveralls-python/blob/661e0f54fcfd98472d3cf97df98f2a1a85242b9c/coveralls/git.py#L85
      - docker-compose exec \
        -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" \
        -e TRAVIS_BRANCH="$TRAVIS_BRANCH" \
        -e GIT_BRANCH="$TRAVIS_BRANCH" \
        -e GIT_ID=10000 \
        -e GIT_AUTHOR_NAME=Cuenca \
        -e GIT_AUTHOR_EMAIL=dev@cuenca.com \
        -e GIT_COMMITTER_NAME=Cuenca \
        -e GIT_COMMITTER_EMAIL=dev@cuenca.com \
        -e GIT_MESSAGE="$TRAVIS_COMMIT_MESSAGE" \
        arcusd coveralls
