notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python

sudo: required

services:
  - docker

jobs:
  include:
  - stage: docker build and test
    python: 3.6
    before_install:
      - cp env.template .env
    # env variables taken from
    # https://github.com/coveralls-clients/coveralls-python/blob/661e0f54fcfd98472d3cf97df98f2a1a85242b9c/coveralls/git.py#L85
      - echo TRAVIS_JOB_ID=$TRAVIS_JOB_ID >> .env
      - echo TRAVIS_BRANCH=$TRAVIS_BRANCH >> .env
      - echo GIT_BRANCH=$TRAVIS_BRANCH >> .env
      - echo GIT_ID=10000 >> .env
      - echo GIT_AUTHOR_NAME=Cuenca >> .env
      - echo GIT_AUTHOR_EMAIL=dev@cuenca.com >> .env
      - echo GIT_COMMITTER_NAME=Cuenca >> .env
      - echo GIT_COMMITTER_EMAIL=dev@cuenca.com >> .env
      - echo GIT_MESSAGE=$TRAVIS_COMMIT_MESSAGE >> .env
    script:
      - make travis-test
    after_failure:
      - docker-compose logs arcusd
