notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python
python: 3.6

sudo: required

services:
  - docker

jobs:
  include:
  - stage: docker build and test
    script:
      - make travis-test
  - stage: code coverage
    script:
      - make code-coverage-upload
      - make docker-stop
