notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python
python: 3.6
sudo: required

script: make travis-test

jobs:
  include:
  - stage: test
    python: 3.6
  - stage: test
    python: 3.7
    dist: xenial
    sudo: true
  - stage: code coverage
    python: 3.6
    install: pip install coveralls
    script:
      - coverage run --source arcusd -m py.test
      - coverage report -m
      - coveralls
