version: '3'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  arcusd:
    build: .
    tty: true
    volumes:
      - .:/arcusd
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - COVERALLS_REPO_TOKEN
      - ARCUS_API_KEY
      - ARCUS_SECRET_KEY
