version: '3'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  arcusd:
    build: .
    tty: true
    volumes:
      - .:/arcusd
    ports:
      - 3000:3000
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - COVERALLS_REPO_TOKEN
      - ARCUS_API_KEY
      - ARCUS_SECRET_KEY
      - ARCUS_USE_SANDBOX